/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Observer: (typeof import('./../components/observer/observer.vue'))['default']
    SfImage: (typeof import('@/snowflake-ui/image/image.vue'))['default']
    SfLazyLoad: (typeof import('@/snowflake-ui/lazyLoad/lazyLoad.vue'))['default']
    SfPage: (typeof import('@/snowflake-ui/page/page.vue'))['default']
    SfQuotation: (typeof import('@/snowflake-ui/quotation/quotation.vue'))['default']
    SfSafeArea: (typeof import('@/snowflake-ui/safeArea/safeArea.vue'))['default']
    SfSetItem: (typeof import('@/snowflake-ui/setItem/setItem.vue'))['default']
    SfSkeleton: (typeof import('@/snowflake-ui/skeleton/skeleton.vue'))['default']
    SfVirtualList: (typeof import('@/snowflake-ui/virtualList/virtualList.vue'))['default']
  }
}
