/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Obj: typeof import('./../components/obj.vue')['default']
    SfImage: typeof import('@/snowflake-ui/image/image.vue')['default']
  }
}
